package parser

// BracketPair represents a pair of Unicode characters forming a bracket pair.
type BracketPair struct {
	o rune
	c rune
}

// UAX9BracketPairs is the list of bracket pairs from
// https://www.unicode.org/Public/UCD/latest/ucd/BidiBrackets.txt
var UAX9BracketPairs = []BracketPair{
	BracketPair{o: '(', c: ')'},
	BracketPair{o: '[', c: ']'},
	BracketPair{o: '{', c: '}'},
	BracketPair{o: '༺', c: '༻'},
	BracketPair{o: '༼', c: '༽'},
	BracketPair{o: '᚛', c: '᚜'},
	BracketPair{o: '⁅', c: '⁆'},
	BracketPair{o: '⁽', c: '⁾'},
	BracketPair{o: '₍', c: '₎'},
	BracketPair{o: '⌈', c: '⌉'},
	BracketPair{o: '⌊', c: '⌋'},
	BracketPair{o: '〈', c: '〉'},
	BracketPair{o: '❨', c: '❩'},
	BracketPair{o: '❪', c: '❫'},
	BracketPair{o: '❬', c: '❭'},
	BracketPair{o: '❮', c: '❯'},
	BracketPair{o: '❰', c: '❱'},
	BracketPair{o: '❲', c: '❳'},
	BracketPair{o: '❴', c: '❵'},
	BracketPair{o: '⟅', c: '⟆'},
	BracketPair{o: '⟦', c: '⟧'},
	BracketPair{o: '⟨', c: '⟩'},
	BracketPair{o: '⟪', c: '⟫'},
	BracketPair{o: '⟬', c: '⟭'},
	BracketPair{o: '⟮', c: '⟯'},
	BracketPair{o: '⦃', c: '⦄'},
	BracketPair{o: '⦅', c: '⦆'},
	BracketPair{o: '⦇', c: '⦈'},
	BracketPair{o: '⦉', c: '⦊'},
	BracketPair{o: '⦋', c: '⦌'},
	BracketPair{o: '⦍', c: '⦐'},
	BracketPair{o: '⦏', c: '⦎'},
	BracketPair{o: '⦑', c: '⦒'},
	BracketPair{o: '⦓', c: '⦔'},
	BracketPair{o: '⦕', c: '⦖'},
	BracketPair{o: '⦗', c: '⦘'},
	BracketPair{o: '⧘', c: '⧙'},
	BracketPair{o: '⧚', c: '⧛'},
	BracketPair{o: '⧼', c: '⧽'},
	BracketPair{o: '⸢', c: '⸣'},
	BracketPair{o: '⸤', c: '⸥'},
	BracketPair{o: '⸦', c: '⸧'},
	BracketPair{o: '⸨', c: '⸩'},
	BracketPair{o: '〈', c: '〉'},
	BracketPair{o: '《', c: '》'},
	BracketPair{o: '「', c: '」'},
	BracketPair{o: '『', c: '』'},
	BracketPair{o: '【', c: '】'},
	BracketPair{o: '〔', c: '〕'},
	BracketPair{o: '〖', c: '〗'},
	BracketPair{o: '〘', c: '〙'},
	BracketPair{o: '〚', c: '〛'},
	BracketPair{o: '﹙', c: '﹚'},
	BracketPair{o: '﹛', c: '﹜'},
	BracketPair{o: '﹝', c: '﹞'},
	BracketPair{o: '（', c: '）'},
	BracketPair{o: '［', c: '］'},
	BracketPair{o: '｛', c: '｝'},
	BracketPair{o: '｟', c: '｠'},
	BracketPair{o: '｢', c: '｣'},
}
