package bidi

// bracketPair represents a pair of Unicode characters forming a bracket pair.
type bracketPair struct {
	o rune
	c rune
}

// UAX9bracketPairs is the list of bracket pairs from
// https://www.unicode.org/Public/UCD/latest/ucd/BidiBrackets.txt
var uax9BracketPairs = []bracketPair{
	bracketPair{o: '(', c: ')'},
	bracketPair{o: '[', c: ']'},
	bracketPair{o: '{', c: '}'},
	bracketPair{o: '༺', c: '༻'},
	bracketPair{o: '༼', c: '༽'},
	bracketPair{o: '᚛', c: '᚜'},
	bracketPair{o: '⁅', c: '⁆'},
	bracketPair{o: '⁽', c: '⁾'},
	bracketPair{o: '₍', c: '₎'},
	bracketPair{o: '⌈', c: '⌉'},
	bracketPair{o: '⌊', c: '⌋'},
	bracketPair{o: '〈', c: '〉'},
	bracketPair{o: '❨', c: '❩'},
	bracketPair{o: '❪', c: '❫'},
	bracketPair{o: '❬', c: '❭'},
	bracketPair{o: '❮', c: '❯'},
	bracketPair{o: '❰', c: '❱'},
	bracketPair{o: '❲', c: '❳'},
	bracketPair{o: '❴', c: '❵'},
	bracketPair{o: '⟅', c: '⟆'},
	bracketPair{o: '⟦', c: '⟧'},
	bracketPair{o: '⟨', c: '⟩'},
	bracketPair{o: '⟪', c: '⟫'},
	bracketPair{o: '⟬', c: '⟭'},
	bracketPair{o: '⟮', c: '⟯'},
	bracketPair{o: '⦃', c: '⦄'},
	bracketPair{o: '⦅', c: '⦆'},
	bracketPair{o: '⦇', c: '⦈'},
	bracketPair{o: '⦉', c: '⦊'},
	bracketPair{o: '⦋', c: '⦌'},
	bracketPair{o: '⦍', c: '⦐'},
	bracketPair{o: '⦏', c: '⦎'},
	bracketPair{o: '⦑', c: '⦒'},
	bracketPair{o: '⦓', c: '⦔'},
	bracketPair{o: '⦕', c: '⦖'},
	bracketPair{o: '⦗', c: '⦘'},
	bracketPair{o: '⧘', c: '⧙'},
	bracketPair{o: '⧚', c: '⧛'},
	bracketPair{o: '⧼', c: '⧽'},
	bracketPair{o: '⸢', c: '⸣'},
	bracketPair{o: '⸤', c: '⸥'},
	bracketPair{o: '⸦', c: '⸧'},
	bracketPair{o: '⸨', c: '⸩'},
	bracketPair{o: '〈', c: '〉'},
	bracketPair{o: '《', c: '》'},
	bracketPair{o: '「', c: '」'},
	bracketPair{o: '『', c: '』'},
	bracketPair{o: '【', c: '】'},
	bracketPair{o: '〔', c: '〕'},
	bracketPair{o: '〖', c: '〗'},
	bracketPair{o: '〘', c: '〙'},
	bracketPair{o: '〚', c: '〛'},
	bracketPair{o: '﹙', c: '﹚'},
	bracketPair{o: '﹛', c: '﹜'},
	bracketPair{o: '﹝', c: '﹞'},
	bracketPair{o: '（', c: '）'},
	bracketPair{o: '［', c: '］'},
	bracketPair{o: '｛', c: '｝'},
	bracketPair{o: '｟', c: '｠'},
	bracketPair{o: '｢', c: '｣'},
}
